dist: precise

language: python

python:
  - "3.5"

addons:
  apt:
    packages:
      - gfortran
      - libboost-random-dev
      - python3.2-dev
      - python3-numpy
      - swig
  
install:
  - pip install -r requirements.txt

script:
  - make test

